name: Postman Package Creation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update fedora
        run: |
          dnf upgrade -y

      - name: Install dependencies
        run: |
          dnf install -y @rpm-development-tools curl rpmdevtools rpm-build rpmlint

      - name: Run script
        id: rpm-step
        run: |
          chmod +x ./make-package.sh
          ./make-package.sh
      - name: Upload created package
        uses: actions/upload-artifact@v4
        with:
          path: ${steps.rpm-step.outputs.PACKAGE_NAME}

