name: Postman Package Creation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Fedora
        run: |
          dnf upgrade -y

      - name: Install dependencies
        run: |
          dnf install -y @rpm-development-tools curl rpmdevtools rpm-build rpmlint

      - name: Run script to build package
        id: build_package
        run: |
          chmod +x ./make-package.sh
          PACKAGE_NAME=$(./make-package.sh)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Upload created package
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ${{ env.PACKAGE_NAME }}
